header = """
/* filcrypto_helpers_ffi Header */

#ifdef __cplusplus
extern "C" {{
#endif
"""
trailer = """
#ifdef __cplusplus
} /* extern "C" */
#endif
"""

include_guard = "FILCRYPTO_HELPERS_FFI_H"
include_version = true
language = "C"

[export]
prefix = "filcrypto_helpers_ffi_"

[parse]
parse_deps = true
include = ["filcrypto-helpers"]
